### ISSUE TITLE
[建议]添加对微动开关的支持

### ISSUE THREAD

**Issue by LoaderTime** [HelloworldDk/HWDK_PROJ_BLUELIGHT#1]
您好，我目前在使用微动开关作为控制器的按键方案，由于是小台，目前还未找到适用的光电开关方案（微动开关比光电开关省钱一点，大概是三四块的差距）
刷入蓝色光程序后，配置器，灯光，串口通信，使用光电开关的键盘部分均工作正常
但意外的是，接上微动开关后，程序无法正常检测微动开关是否触发，无法在此基础上使用键盘功能（com端接gnd，no端接pa4）
因为蓝色光项目拥有的灯光分组功能减少了大量由接线带来的麻烦，并且整个项目的主要目的是灯光+键盘二合一，所以希望可以添加对微动开关的支持，兼容更多可行的控制器方案

**Comment by HelloworldDk** [comment]
这板子本来就是给mai用的倒是，是团队内部的东西，友情开源的来着
不过说到微动，在key1-8可以通过微动com接gnd，常闭nc段接信号针脚使用，而以外的接口本身设计就是微动，com接gnd，信号接no常开即可
无需另加适配
如果需要将1-8改为9那样的，按下是接通的微动解法，则程序读取按键部分1-8前面的叹号去掉就行

**Comment by HelloworldDk** [comment]
这玩意本身没考虑过整其他游戏，虽然本身可以那么整，整全游戏支持应该是另一个现在并不想做的项目的事情（x）

但是其实蓝色光还有个音击的程序，具体就是支持霍尔磁角度传感器作为摇和微动按键输入，mai按键作为侧键的xinput程序没有公开，使用效果也不错，需要的话我可以公开一下？

**Comment by LoaderTime** [comment]
谢谢，问题解决了，没想过接nc（常闭）端，是我太“那个”了（

关于音击的程序，我在想着是否可以以此程序为基础改造我现在那个音击的控制器（毕竟stm32的性能对我这种经常用arduino的人来说实在太有诱惑力了），所以如果可以的话，能否公开一下程序？谢谢

**Comment by HelloworldDk** [comment]
> 谢谢，问题解决了，没想过接nc（常闭）端，是我太“那个”了（
> 
> 关于音击的程序，我在想着是否可以以此程序为基础改造我现在那个音击的控制器（毕竟stm32的性能对我这种经常用arduino的人来说实在太有诱惑力了），所以如果可以的话，能否公开一下程序？谢谢

蓝色光互换音击材料已经上传
